version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    command: gunicorn -b 0.0.0.0:5000 run:app
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/instance:/app/instance

  frontend:
    build:
      context: ./react_frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"  # Expose on 3000 locally, Nginx inside serves on 80

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
