version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    command: gunicorn -b 0.0.0.0:5000 run:app
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/instance:/app/instance
    # Internal service, no public ports

  frontend:
    build:
      context: ./react_frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/certbot:/var/www/certbot  # ✅ Certbot challenge directory
      - /etc/letsencrypt:/etc/letsencrypt  # ✅ SSL certs directory

